[tool.poetry]
name = "quizx"
version = "0.0.0-alpha.1"
description = "Quantum Circuit Optimisation and Compilation using the ZX-calculus"
classifiers = [] # TODO
authors = ["Aleks Kissinger <aleks0@gmail.com>"]
maintainers = [
    "Aleks Kissinger <aleks0@gmail.com>",
    "Agustin Borgna <agustinborgna@gmail.com>",
]
include = ["pyproject.toml"]
license = "Apache-2.0"
readme = "README.md"

packages = [{ include = "pybindings" }]

[tool.poetry.dependencies]
python = ">=3.10"
pyzx = "0.8.0"

[tool.poetry.group.dev.dependencies]
maturin = "^1.5.1"
pytest = "^8.1.1"
ruff = "^0.3.4"
pre-commit = "^3.7.0"
mypy = "^1.9.0"

[build-system]
requires = ["maturin~=1.5.1"]
build-backend = "maturin"

[project]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Software Development :: Compilers",
    "Development Status :: 3 - Alpha",
]
name = "quizx"
version = "0.0.0-alpha.1"
description = "Quantum Circuit Optimisation and Compilation using the ZX-calculus"
authors = [{ name = "Aleks Kissinger", email = "aleks0@gmail.com" }]
maintainers = [
    { name = "Aleks Kissinger", email = "aleks0@gmail.com" },
    { name = "Agustin Borgna", email = "agustinborgna@gmail.com" },
]
requires-python = ">=3.10"
license = { file = "LICENSE" }

[project.urls]
homepage = "https://github.com/Quantomatic/quizx"
repository = "https://github.com/Quantomatic/quizx"

[tool.maturin]
manifest-path = "pybindings/Cargo.toml"
python-source = "pybindings"
