[package]
name = "quizx"
default-example = "hidden_shift_stabrank"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
license-file = { workspace = true }

[dependencies]
num = { workspace = true }
rustc-hash = { workspace = true }
rayon = { workspace = true }
ndarray = { workspace = true, features = ["rayon"] }
approx = { workspace = true }
regex = { workspace = true }
rand = { workspace = true }
itertools = { workspace = true }
openqasm = { workspace = true }
